# Generated by Django 4.1.2 on 2022-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstore',
            name='site_url',
            field=models.URLField(max_length=520),
        ),
    ]
