# Generated by Django 4.1.2 on 2022-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_alter_passwordstore_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordstore',
            name='key',
            field=models.TextField(default='sdasd'),
            preserve_default=False,
        ),
    ]
