# Generated by Django 4.1.2 on 2022-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_passwordstore_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstore',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
