# Generated by Django 4.1.2 on 2022-10-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_passwordstore_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordstore',
            name='key',
        ),
    ]
