# Generated by Django 4.1.2 on 2022-11-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_remove_passwordstore_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordstore',
            old_name='site_name',
            new_name='title',
        ),
    ]
